@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to publish sale announcement
    activate System 
        System --> Agent : requests whether the agent wants to create a new one\nor approve one that a user submitted through the application
    deactivate System

    Agent -> System : selects to create a new property listing
    activate System 
        System --> Agent : request property information\n(area, location, distance from city center, price)
    deactivate System
    
    Agent -> System : submits requested data
    activate System 
        System --> Agent : lists possible types of property\nand request that one is selected
    deactivate System
    
    Agent -> System : selects one of the available options (house, apartment, land)
    alt property = house or apartment
    activate System 
        System --> Agent : requests specific data related to selection\n(number of bedrooms, number of bathrooms,\nnumber of parking spaces, availabe equipment)
    else property = house
        System --> Agent : request additional characteristics\n(existing basement, inhabitable loft, sun exposure)
    deactivate System

    Agent -> System : submits requested data
    activate System 
    end
        System --> Agent : requests photographs to append
    deactivate System

    Agent -> System : submits requested information
    activate System 
        System --> Agent : requests comission information
    deactivate System

    Agent -> System : submits requested information
    activate System 
        System --> Agent : display operation success
    deactivate System

@enduml
/' 
    Agent -> System : 
    activate System 
        System --> Agent : 
    deactivate System '/