@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant ":ListPropertiesController" as CTRL
participant ":Repositories" as ORG
participant "repositories\n:Repositories" as REPO
participant "propertyTypeRepository\n:PropertyTypeRepository" as PropertyTypeRepository

autonumber 12
-> CTRL : getPropertyTypeList()

autonumber 12.1

activate CTRL
    group Get Property Type List

        CTRL -> REPO : getPropertyTypeRepository()
        activate REPO

        REPO --> CTRL: propertyTypeRepository
        deactivate REPO

        CTRL -> PropertyTypeRepository: getPropertyTypeList()
        activate PropertyTypeRepository

        PropertyTypeRepository --> CTRL: propertyTypeList
        deactivate PropertyTypeRepository



    end group

    autonumber 13
    <-- CTRL: propertyTypeList

deactivate CTRL


@enduml