@startuml
'https://plantuml.com/class-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
hide circle
hide methods



class Employee{
    idEmployee
    name
    numberCitizen
    numberTax
    address
    email
    phoneNumber
}

class Client {
    idClient
    name
    phoneNumber
    numberCitizen
    numberTax
    email
    address
}

class Owner {
    idOwner
    email
    name
    numberCitizen
    numberTax
    address
    phoneNumber
}


class Agent {
    idCodAgent
    idCodStore
}

class Advertisement {
    idOwner
    propertyType
    areaProperty
    distanceCityCenter
    location
    conditionProperty
    photos
    verified
    idAdvertisement
    idCodAgent
    propertyCode
}

class House {
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
    basement
    loft
    sunExposure
}

class Apartment{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}

class Land{
    description
}

class Store{
    idCodStore
    idStoreNetworkManager
    nameStore
    location
    idStoreManager
    emailStore
    contactStore
}

class Visit{
    idAdvertisement
    idCodClient
    idVisit
    report
}

class Location {
    zipCode
    stateUS
    county
    city
}

class StoreManager {
    idStoreManager
    idCodStore
}

class StoreNetworkManager {
    idStoreNetworkManager
}



class Request{
    idRequest
    idAdvertisement
    idCodClient
    offer
}
class User{
    email
    password
}

Owner "1" -- "*" Advertisement
Agent "1" -- "*" Advertisement
House "1" -- "1" Advertisement
Apartment "1" -- "1" Advertisement
Land "1" -- "1" Advertisement
Store "1" -- "*" Agent
StoreManager "1" -- "1" Store
Advertisement "1" -- "1" Location
StoreNetworkManager "1" -- "*" Store
Employee "1" -- "1" Agent
Employee "1" -- "1" StoreManager
Employee "1" -- "1" StoreNetworkManager
Advertisement"1" -- "*"Request
Client"1" -- "*"Request
Store"1" -- "1"Location
Advertisement "1" -- "*" Visit
Client "1" -- "*" Visit
Agent "1" -- "*" Visit
User "1" -- "1" Employee
User "1" -- "1" Owner
User "1" -- "1" Client

@enduml