@startuml
'https://plantuml.com/class-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
hide circle
hide methods

class Network{

}

class Employee{
    name
    numberCitizen
    numberTax
    location
    email
    phoneNumber
}
class Client {
    idCodClient
    idCodStore
    nameClient
    contactClient
    idNumbCard
    idNumFin
    emailClient
    adressClient
    location
}

class Owner {
    name
    numberCitizen
    numberTax
    address
    email
    phoneNumber
}
class VisitsReport{
    idVisit
    report
}

class Agent {
    idCodAgent
    idCodStore
}

class Property {
    propertyCode
    propertyType
    areaProperty
    distanceCityCenter
    location
    conditionProperty
    photos
}

class House {
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
    basement
    loft
    sunExposure
}

class Apartment{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}
class Land{
    description
}

class Rent {
    rentMonth
    durationOfContract
}
class Sale {
    salePrice
}
class CommissionFixed {
    commissionPropertyAmount
}
class CommissionPercent {
    commissionPropertyPercent
}

class Store{
    idCodStore
    nameStore
    location
    idStoreManager
    emailStore
    contactStore
}
class Visit{
    idAdvertisement
    idCodClient
    idVisit
}
class Location {
    zipCode
    stateUS
    county
    city
}
class StoreManager {
    idStoreManager
    idCodStore
}
class StoreNetworkManager {
    idStoreNetworkManager
}
class Advertisement{
    idAdvertisement
    idCodAgent
    propertyCode
}
class Request{
    idRequest
    idAdvertisement
    idCodClient
    offer
}

Property "1" -- "1" Advertisement
Owner "1" -- "*" Property
Agent "1" -- "*" Advertisement
House "1" -- "1" Property
Apartment "1" -- "1" Property
Land "1" -- "1" Property
Store "1" -- "*" Agent
Rent "0..1" -- "1" Advertisement
Sale "0..1" -- "1" Advertisement
StoreManager "1" -- "1" Store
Property "1" -- "1" Location
Agent "0..1" -- "1" CommissionFixed
Agent "0..1" -- "1" CommissionPercent
Network "1" -- "*" Store
StoreNetworkManager "1" -- "1" Network
Employee "1" -- "1" Agent
Employee "1" -- "1" StoreManager
Employee "1" -- "1" StoreNetworkManager
Advertisement"1" -- "*"Request
Client"1" -- "*"Request
Store"1" -- "1"Location
Advertisement "1" -- "*" Visit
Advertisement "1" -- "*" VisitsReport
Client "1" -- "*" Visit
Agent "1" -- "*" Visit




@enduml