@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Owner {
    idOwner
    email
    name
    numberCitizen
    tin
    location
    phoneNumber
}

class Property {
    idCodProperty
    propertyType
    adressProperty
    areaProperty
    distanceCityCenter
    idLocation
    idCodAgent
    rentOrSale
    conditionProperty
    comProperty
    photos
}

class House{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
    basement
    loft
    sunExposure
}

class Apartment{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}

class Land{
    description
}
class Rent {
    rentMonth
    durationOfContract
}
class Sale {
    salePrice
}

class Location {
    address
    doorNumber
    floor
    side
    zipCode
    stateUS
    county
    city

}

class Agent {
    idCodAgent
    idCodStore
    commission
}

class Store{
    idCodStore
    idStoreNetworkManager
    nameStore
    location
    idStoreManager
    emailStore
    contactStore
    commission

}

Owner "1" -- "1..*" Property: owns >
Owner "1" -- "1..*" Agent: choses >
Owner "1" -- "1" Store: choses >
Owner "1" -- "*" Property : creates >
Property "*" -- "1" House: cataloged as >
Property "*" -- "1" Apartment: cataloged as >
Property "*" -- "1" Land: cataloged as >
Property "*" -- "1" Rent: cataloged as >
Property "*" -- "1" Sale: cataloged as >
Property "*" -- "1" Location: has >
Store "*" -- "1" Location: has >

@enduml