@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

'title Use Case Diagram Example

left to right direction

usecase "UC1 - List of Properties" as UC1
User --> UC1
usecase "UC2 - Publish Sale Announcements" as UC2
Agent --> UC2
usecase "UC3 - Register Employees" as UC3
"System Administrator" --> UC3
usecase "UC4 - Request for Listing a Property Sale or Rent" as UC4
Owner-->UC4


@enduml