@startuml
'https://plantuml.com/class-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
hide circle
hide methods


class Employee{
    name
    numberCitizen
    tin
    email
    phoneNumber
}

class Client {
    name
    phoneNumber
    numberCitizen
    tin
    email
}

class Owner {
    email
    name
    numberCitizen
    tin
    phoneNumber
}

class Agent {
    commission
}

class Advertisement {
    idAdvertisement
    salePrice
    durationOfContract
    rentalPrice
    state
}

class PropertyType{
    designation
}

class Property{
    areaProperty
    distanceCityCenter
    conditionProperty
    photos
    propertyCode
}

class House {
    basement
    loft
    sunExposure
}

class Building{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}


class Store{
    idCodStore
    nameStore
    emailStore
    contactStore
}

class Visit{
    idVisit
    report
}

class Location {
    street
    zipCode
    stateUS
    city
    district
}

class StoreManager {
}

class StoreNetworkManager {
}

class Request{
    idRequest
    offer
}

class SystemAdministrator{
    idAdmin
}

class UnregisteredUser

Owner "1" -- "1..*" Property: owns >
Agent "1" -- "*" Advertisement: publishes and is in charge of >
House --|> Building

Building --|> Property
Store "1" -- "*" Agent: works <
StoreManager "1" -- "1" Store:  monitors >
Property "1" -- "1" Location: owns >
StoreNetworkManager "1" -- "*" Store:  analyzes >
Employee <|-- Agent
Employee <|-- StoreManager
Employee <|-- StoreNetworkManager
Advertisement"1" -- "*"Request: receives >
Client"1" -- "*"Request: makes >
Store"1" -- "1"Location: owns >
Advertisement "1" -- "*" Visit: hosts >
Client "1" -- "*" Visit: requests >
Agent "1" -- "*" Visit: schedules and carries out >
Property "1" - "1" Advertisement: represents <
Client "1" -- "1" Location: owns >
Employee "1" -- "1" Location: owns >
Owner "1" -- "1" Location: owns >
Store "1" -- "*" Advertisement: contains >
UnregisteredUser "1" -- "*" Advertisement: searches >
SystemAdministrator "1" -- "*" Store: creates >
SystemAdministrator "1" -- "*" Employee: creates >
Client "*" -- "*" Advertisement: searches >
Employee <|-- SystemAdministrator
Owner "1" - "*" Advertisement: asks to create >
PropertyType "1" -- "*" Property


@enduml