@startuml
'https://plantuml.com/class-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
hide circle
hide methods


class Employee{
    name
    numberCitizen
    tin
    email
    phoneNumber
}

class Client {
    name
    phoneNumber
    numberCitizen
    tin
    email
}

class Owner {
    email
    name
    numberCitizen
    tin
    phoneNumber
}

class Agent {
    commission
}

class Advertisement {
    idAdvertisement
    salePrice
    durationOfContract
    rentalPrice
}

class Property{
    propertyType
    areaProperty
    distanceCityCenter
    conditionProperty
    photos
    propertyCode
}

class House {
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
    basement
    loft
    sunExposure
}

class Apartment{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}

class Land

class Store{
    idCodStore
    nameStore
    emailStore
    contactStore
    commission
}

class Visit{
    idVisit
    report
}

class Location {
    street
    zipCode
    stateUS
    city
    district
}

class StoreManager {
}

class StoreNetworkManager {
}

class Request{
    idRequest
    offer
}

class SystemAdministrator{
    idAdmin
}

class UnregisteredUser

Owner "1" -- "1..*" Property: owns >
Agent "1" -- "*" Advertisement: publish and is in charge of >
House --|> Property
Apartment --|> Property
Land --|>  Property
Store "1" -- "*" Agent: works <
StoreManager "1" -- "1" Store:  monitor >
Property "1" -- "1" Location: owns >
StoreNetworkManager "1" -- "*" Store:  analyze >
Employee <|-- Agent
Employee <|-- StoreManager
Employee <|-- StoreNetworkManager
Advertisement"1" -- "*"Request: receives >
Client"1" -- "*"Request: make >
Store"1" -- "1"Location: owns >
Advertisement "1" -- "*" Visit: hosts >
Client "1" -- "*" Visit: request >
Agent "1" -- "*" Visit: schedule and carry >
Property "1" - "1" Advertisement: represents <
Client "1" -- "1" Location: owns >
Employee "1" -- "1" Location: owns >
Owner "1" -- "1" Location: owns >
Agent "1" -- "1" Property: verifies >
Store "1" -- "*" Advertisement: contains >
UnregisteredUser "1" -- "*" Advertisement: search >
SystemAdministrator "1" -- "*" Store: create >
SystemAdministrator "1" -- "*" Employee: create >
Client "*" -- "*" Advertisement: search >
Employee <|-- SystemAdministrator

@enduml