@startuml
'https://plantuml.com/class-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
hide circle
hide methods



class Employee{
    idEmployee
    name
    numberCitizen
    numberTax
    location
    email
    phoneNumber
}

class Client {
    idClient
    name
    phoneNumber
    numberCitizen
    numberTax
    email
    location
}

class Owner {
    idOwner
    email
    name
    numberCitizen
    numberTax
    location
    phoneNumber
}

class Agent {
    idCodAgent
    idCodStore
}

class Advertisement {
    idAdvertisement
    idCodAgent
    propertyCode
}

class Property{
    idOwner
    propertyType
    areaProperty
    distanceCityCenter
    location
    conditionProperty
    photos
    propertyCode
}

class House {
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
    basement
    loft
    sunExposure
}

class Apartment{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}

class Land{
    description
}

class Store{
    idCodStore
    idStoreNetworkManager
    nameStore
    location
    idStoreManager
    emailStore
    contactStore
}

class Visit{
    idAdvertisement
    idCodClient
    idVisit
    report
}

class Location {
    address
    doorNumber
    floor
    side
    zipCode
    stateUS
    county
    city
}

class StoreManager {
    idStoreManager
    idCodStore
}

class StoreNetworkManager {
    idStoreNetworkManager
}

class Request{
    idRequest
    idAdvertisement
    idCodClient
    offer
}
class User{
    email
    password
}

Owner "1" -- "1..*" Property: owns >
Agent "1" -- "*" Advertisement: publish >
House "1" -- "1" Property: is >
Apartment "1" -- "1" Property: is >
Land "1" -- "1"  Property: is >
Store "1" -- "*" Agent: works <
StoreManager "1" -- "1" Store:  monitor >
Property "1" -- "1" Location: has >
StoreNetworkManager "1" -- "*" Store:  analyzes >
Employee "1" -- "1" Agent: is <
Employee "1" -- "1" StoreManager: is <
Employee "1" -- "1" StoreNetworkManager: is <
Advertisement"1" -- "*"Request: receives >
Client"1" -- "*"Request: make >
Store"1" -- "1"Location: has >
Advertisement "1" -- "*" Visit: has >
Client "1" -- "*" Visit: make >
Agent "1" -- "*" Visit: schedule and carry >
User "1" -- "1" Employee: is <
User "1" -- "1" Owner: is <
User "1" -- "1" Client: is <
Property "1" - "1" Advertisement: is used in >
Client "1" -- "1" Location: has >
Employee "1" -- "1" Location: has >
Owner "1" -- "1" Location: has >
Agent "1" -- "1" Property: verifies >
Store "1" -- "*" Advertisement: contains >

@enduml