@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Client {
    idCodClient
    idCodStore
    nameClient
    contactClient
    idNumbCard
    idNumFin
    emailClient
    adressClient
    idLocation
}
Client "1" -down "0....*" Agent : has >
Client "1" -down "1" Location : has >

class Owner {
    idCodOwner
    nameOwner
    contactOwner
    idNumbCard
    idNumFin
    emailOwner
    idCodOwner
    numProperties
    adressOwner
    idLocation
}
Owner "1" -down "0....*" Agent : has >
Owner "1" -down "1" Location : has >

class Agent {
    idCodAgent
    idCodStore
    nameAgent
    idNumbCard
    idNumFin
    adressAgent
    emailAgent
    contactAgent
    idLocation
}
Agent "1" -down "1" Location : has >

class Property {
    idCodProperty
    propertyType
    adressProperty
    areaProperty
    distanceCityCenter
    idLocation
    idCodAgent
    rentOrSale
    conditionProperty
    comProperty
    photos
}
Property "1" -down "1" Rent : has >
Property "1" -down "1" Sale : has >
Property "1" -down "1" CommissonFixed : has >
Property "1" -down "1" CommissonPercent : has >
Property "1" -down "1" Location : has >
Property "1" -down "1" House : can be >
Property "1" -down "1" Apartment : can be >
Property "1" -down "1" Land : can be >

class House {
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
    basement
    loft
    sunExposure
}
class Apartment{
    numberBedrooms
    numberBathrooms
    numberParking
    availableEquipment
}
class Land{
    description
}
class Rent {
    rentMonth
    durationOfContract
}
class Sale {
    salePrice
}
class CommissonFixed {
    commissonPropertyAmount
}
class CommissonPercent {
    commissonPropertyPercent
}

class Store{
    idCodStore
    idLocation
    idStoreManager
    desigStore
    adressStore
    emailStore
    contactStore
}
Store "1" -down "1" Location : has >
Store "1" -down "0...*" Agent : has >
Store "1" -down "1" StoreManager : has >

class Visit{
    idCodAgent
    idcodclient
    idCodProperty
    idCodVisit
}
Visit "1" -down "1" Property : has >
Visit "1" -down "1" Client : has >
Visit "1" -down "1" Agent : has >

class Location {
    zipCode
    stateUS
    county
    city
}

class StoreManager {
    idStoreManager
    nameStoreManager
    idNumbCard
    idNumFin
    adressStoreManager
    emailStoreManager
    contactStoreManager
    idLocation
}
StoreManager "1" -down "1" Location : has >

class StoreNetworkManager {
    idStoreManager
    nameStoreManager
    idNumbCard
    idNumFin
    adressStoreManager
    emailStoreManager
    contactStoreManager
    idLocation
}
StoreNetworkManager "1" -down "1" Location : has >
StoreNetworkManager "1" -down "0...*" Store : has >

@enduml