@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Property Owner" as User
participant ":SubmitPropertytUI" as UI
participant ":SubmitPropertyController" as CTRL

' LOG IN
participant "personRepository\n:PersonRepository" as personRepository

' SUBMIT PROPERTY
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

participant "propertyRepository\n:PropertyRepository" as propertyRepository
participant "propertyRepository\n:PropertyRepository" as propertyRepository

participant "propertyTypeRepository\n:PropertyTypeRepository" as propertyTypeRepository
participant "businessTypeRepository\n:BusinessTypeRepository" as BusinessTypeRepository

' CHOOSE A AGENT
participant "storesRepository\n:StoresRepository" as stores
participant "personRepository\n:PersonRepository" as personRepository

activate User


 ' SUBMIT PROPERTY
    User -> UI : asks to submit new property
        activate UI

          UI -> CTRL** : create
                activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

            CTRL --> UI: repositories
            deactivate CTRL

'   UI --> User : requests data (Property Type)

        UI  ->  CTRL : getPropertyTypes()
            activate CTRL

            CTRL  ->  RepositorySingleton : getPropertyTypes()
                activate RepositorySingleton

                RepositorySingleton --> CTRL: getPropertyTypes()
                deactivate RepositorySingleton

            CTRL -> propertyTypeRepository : getPropertyTypes()
                activate propertyTypeRepository

                propertyTypeRepository --> CTRL : PropertyTypesList
                deactivate propertyTypeRepository

            CTRL --> UI : propertyTypeRepository
                deactivate CTRL


            UI --> User : shows propertyType list\n and asks to select one
            deactivate UI

    User -> UI : selects a Property Type
            activate UI

            UI  ->  UI: keep Property Types

alt propertyType = House

            UI -> User : ask data (year, month, day, \narea cms. Distance Kms, \nnumberBedrooms, numberParking, \nbasement, loft)
            deactivate UI

    User -> UI : types asked data (year, month, day, \narea cms. Distance Kms, \nnumberBedrooms, numberParking, \nbasement, loft)
            activate UI

            UI  ->  UI: keep data (year, month, day, \narea cms. Distance Kms, \nnumberBedrooms, numberParking, \nbasement, loft)

    group opt
            UI -> User : ask data (numberBathrooms, \navailableEquipment, sunExposure)
                deactivate UI

        User -> UI : types asked data (numberBathrooms, \navailableEquipment, sunExposure)
                activate UI

            UI  ->  UI: keep data (numberBathrooms, \navailableEquipment, sunExposure)
    end

            UI -> CTRL : getBusinessTypeRepository()
                activate CTRL

                    CTRL -> RepositorySingleton : getBusinessTypeRepository()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                    CTRL -> PLAT : getBusinessTypeRepository()
                    activate PLAT

                        PLAT --> CTRL: BusinessTypeRepository
                        deactivate PLAT

                    CTRL -> BusinessTypeRepository: getBusinessTypeList()
                    activate BusinessTypeRepository

                    BusinessTypeRepository -> CTRL: businessTypeList
                    deactivate BusinessTypeRepository

                    CTRL ->  UI: businessTypeList
                    deactivate CTRL

            UI --> User : shows businessTypeList\n and asks to select one
                deactivate UI

        User -> UI : selects a Business Type
                activate UI

    alt businessType = Sale

            UI -> User : ask data (Sale Price)
            deactivate UI

        User -> UI : types asked data (Sale Price)
            activate UI

            UI  ->  UI: keep data (Sale Price)

    else businessType = Rent

            UI -> User : ask data (Rental Price, Duraction of Contract)
            deactivate UI

        User -> UI : types asked data (Rental Price, Duraction of Contract)
            activate UI

            UI  ->  UI: keep data (Rental Price, Duraction of Contract)

    end

            UI -> User: request data (property Photo)
            deactivate UI

            User -> UI : input asked data (property Photo)
                    activate UI

            UI  ->  UI: keep data (property Photo)

    opt

        loop

            UI -> User: request data (property Photo)
            deactivate UI

        User -> UI : input asked data (property Photo)
                    activate UI

            UI  ->  UI: keep data (property Photo)

        end

    end

            UI -> CTRL : getPropertyRepository()
                activate CTRL

            CTRL -> RepositorySingleton : getPropertyRepository()
                    activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                CTRL -> PLAT : getPropertyRepository()
                activate PLAT

                    PLAT --> CTRL: PropertyRepository
                    deactivate PLAT

                CTRL -> propertyRepository: newHouseProperty()
                activate propertyRepository

                    propertyRepository -> CTRL : newHouseProperty()
                    deactivate propertyRepository

                CTRL -> UI: propertyRepository
                deactivate CTRL

else propertyType = Apartment

            UI -> User : ask data (year, month, day, \narea cms. Distance Kms, \nnumberBedrooms, numberParking)
            deactivate UI

    User -> UI : types asked data (year, month, day, \narea cms. Distance Kms, \nnumberBedrooms, numberParking)
            activate UI

            UI  ->  UI: keep data (year, month, day, \narea cms. Distance Kms, \nnumberBedrooms, numberParking)

group opt
            UI -> User : ask data (numberBathrooms, \navailableEquipment, sunExposure)
            deactivate UI

    User -> UI : types asked data (numberBathrooms, \navailableEquipment, sunExposure)
            activate UI

            UI  ->  UI: keep data (numberBathrooms, \navailableEquipment, sunExposure)

end

            UI -> CTRL : getBusinessTypeRepository()
                activate CTRL

                    CTRL -> RepositorySingleton : getBusinessTypeRepository()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                    CTRL -> PLAT : getBusinessTypeRepository()
                    activate PLAT

                        PLAT --> CTRL: BusinessTypeRepository
                        deactivate PLAT

                    CTRL -> BusinessTypeRepository: getBusinessTypeList()
                    activate BusinessTypeRepository

                    BusinessTypeRepository -> CTRL: businessTypeList
                    deactivate BusinessTypeRepository

                    CTRL ->  UI: businessTypeList
                    deactivate CTRL

            UI --> User : shows businessTypeList\n and asks to select one
                deactivate UI

        User -> UI : selects a Business Type
                activate UI

    alt businessType = Sale

            UI -> User : ask data (Sale Price)
            deactivate UI

        User -> UI : types asked data (Sale Price)
            activate UI

            UI  ->  UI: keep data (Sale Price)

    else businessType = Rent

            UI -> User : ask data (Rental Price, Duraction of Contract)
            deactivate UI

        User -> UI : types asked data (Rental Price, Duraction of Contract)
            activate UI

            UI  ->  UI: keep data (Rental Price, Duraction of Contract)

    end

            UI -> User: request data (property Photo)
            deactivate UI

            User -> UI : input asked data (property Photo)
                    activate UI

            UI  ->  UI: keep data (property Photo)

    opt

        loop

            UI -> User: request data (property Photo)
            deactivate UI

        User -> UI : input asked data (property Photo)
                    activate UI

            UI  ->  UI: keep data (property Photo)

        end

    end

            UI -> CTRL : getPropertyRepository()
                activate CTRL

                CTRL -> RepositorySingleton : getPropertyRepository()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                CTRL -> PLAT : getPropertyRepository()
                activate PLAT

                    PLAT --> CTRL: PropertyApartmentRepository
                    deactivate PLAT

                CTRL -> propertyRepository: newApartmentProperty()
                activate propertyRepository

                    propertyRepository -> CTRL : newApartmentProperty()
                    deactivate propertyRepository

                CTRL -> UI: propertyRepository
                deactivate CTRL

else propertyType = Land

            UI -> User : ask data (year, month, day, \narea cms. Distance Kms, Description)
            deactivate UI

    User -> UI : types asked data (year, month, day, \narea cms. Distance Kms, Description)
            activate UI

            UI  ->  UI: keep data (year, month, day, \narea cms. Distance Kms, Description)

            UI -> CTRL : getBusinessTypeRepository()
                activate CTRL

                    CTRL -> RepositorySingleton : getBusinessTypeRepository()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                    CTRL -> PLAT : getBusinessTypeRepository()
                    activate PLAT

                        PLAT --> CTRL: BusinessTypeRepository
                        deactivate PLAT

                    CTRL -> BusinessTypeRepository: getBusinessTypeList()
                    activate BusinessTypeRepository

                    BusinessTypeRepository -> CTRL: businessTypeList
                    deactivate BusinessTypeRepository

                    CTRL ->  UI: businessTypeList
                    deactivate CTRL

            UI --> User : shows businessTypeList\n and asks to select one
                deactivate UI

        User -> UI : selects a Business Type
                activate UI

    alt businessType = Sale

            UI -> User : ask data (Sale Price)
            deactivate UI

        User -> UI : types asked data (Sale Price)
            activate UI

            UI  ->  UI: keep data (Sale Price)

    else businessType = Rent

            UI -> User : ask data (Rental Price, Duraction of Contract)
            deactivate UI

        User -> UI : types asked data (Rental Price, Duraction of Contract)
            activate UI

            UI  ->  UI: keep data (Rental Price, Duraction of Contract)

    end

            UI -> User: request data (property Photo)
            deactivate UI

            User -> UI : input asked data (property Photo)
                    activate UI

            UI  ->  UI: keep data (property Photo)

    opt

        loop

            UI -> User: request data (property Photo)
            deactivate UI

        User -> UI : input asked data (property Photo)
                    activate UI

            UI  ->  UI: keep data (property Photo)

        end

    end

            UI -> CTRL : getPropertyRepository()
                activate CTRL

                CTRL -> RepositorySingleton : getPropertyRepository()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                CTRL -> PLAT : getPropertyRepository()
                activate PLAT

                    PLAT --> CTRL: PropertyRepository
                    deactivate PLAT

                CTRL -> propertyRepository: newProperty()
                activate propertyRepository

                    propertyRepository -> CTRL : newProperty()
                    deactivate propertyRepository

                CTRL -> UI: propertyRepository
                deactivate CTRL
end
' CREATE PROPERTY




' CHOOSE A AGENT

    User -> UI : asks to choose Agent
        activate UI

        UI  ->  CTRL : getStoreList()
            activate CTRL

            CTRL  ->  RepositorySingleton : getStoreList()
                activate RepositorySingleton

                RepositorySingleton --> CTRL: getStoreList()
                deactivate RepositorySingleton

            CTRL -> stores : getStoreList()
                activate stores

                stores --> CTRL : storeList
                deactivate stores

            CTRL --> UI : storeList
            deactivate CTRL

        UI --> User : shows Store List list\n and asks to select one
        deactivate UI

    User -> UI : selects a Store
        activate UI

        UI  ->  UI: keep store

        UI  ->  CTRL : getAgentList()
            activate CTRL

            CTRL  ->  RepositorySingleton : getAgentList()
                activate RepositorySingleton

                RepositorySingleton --> CTRL: getAgentList()
                deactivate RepositorySingleton

            CTRL -> personRepository : getAgentList()
                activate personRepository

                personRepository --> CTRL : agentList
                deactivate personRepository

            CTRL --> UI : agentList
                deactivate CTRL

        UI --> User : shows Agent List list\n and asks to select one
            deactivate UI

    User -> UI : selects a Agent
        activate UI

        UI  ->  UI: keep Agent

        UI -> User: Display property conditions and ask for validation (YES/NO)
        deactivate UI

    User -> UI: input: validation (YES/NO)
        activate UI

alt validation = YES
        UI -> User : displays operation success, sends document operation details and conclusion
        deactivate UI
end


@enduml