@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Property Owner" as User
participant ":SubmiPropertytUI" as UI
participant ":SubmiPropertyController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "storesRepository\n:StoresRepository" as stores
participant "propertyTypeRepository\n:PropertyTypeRepository" as propertyTypeRepository
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG
participant "task\n:Task" as TAREFA

activate User

        User -> UI : asks to submit new property

        activate UI

'   UI --> User : requests data (Store)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getStores()
            activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getStoresRepository()
            activate PLAT

            PLAT --> CTRL: storesRepository
            deactivate PLAT

            CTRL -> storesRepository : getStores()
            activate storesRepository

            storesRepository --> CTRL : storeList
            deactivate storesRepository

            CTRL --> UI : storeList
            deactivate CTRL

            UI --> User : shows Store list\n and asks to select one
            deactivate UI

    User -> UI : selects a Store
    activate UI
            UI  ->  UI: keep store

'   UI --> User : requests data (Agent)

            UI -> CTRL : getStoresRepository()
            activate CTRL

            CTRL -> PLAT : getStoresRepository()
            activate PLAT

            PLAT --> CTRL: storesRepository
            deactivate PLAT

            CTRL -> storesRepository : getAgentFromStore()
            activate storesRepository

            storesRepository --> CTRL : AgentFromStoreList
            deactivate storesRepository

            CTRL --> UI : AgentFromStoreList
            deactivate CTRL

    User -> UI : selects a Agent From Store
    activate UI
            UI  ->  UI: keep store, agent

'   UI --> User : requests data (Property Type)
            UI  ->  CTRL : getPropertyTypes()
            activate CTRL

            CTRL  ->  RepositorySingleton : getPropertyTypes()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: propertyType
            deactivate RepositorySingleton

            CTRL -> storesRepository : getPropertyTypes()
            activate propertyTypeRepository

            propertyTypeRepository --> CTRL : PropertyTypesList
            deactivate propertyTypeRepository

            CTRL --> UI : propertyTypeRepository
            deactivate CTRL

    User -> UI : selects a Property Type
    activate UI

            UI  ->  UI: keep Store, Agent, Property Types









        UI_ --> ADM_ : requests data
    deactivate UI_

    User_ -> UI_ : types requested data (reference, description, \ninformal description, technical description,\nduration, cost)
    activate UI_

        UI_ --> ADM_ : shows selected category and requested data
    deactivate UI_

    ADM_ -> UI_ : submits data
    activate UI_

        UI_ -> CTRL_ : createTask(reference,\ndescription,\ninformalDescription,\ntechnicalDescription,\nduration, cost,\ntaskCategoryDescription)
        activate CTRL_

            CTRL_ -> CTRL_ : getTaskCategoryByDescription(taskCategoryDescription)
            activate CTRL_

                CTRL_ -> RepositorySingleton_ : getInstance()
                activate RepositorySingleton_

                    RepositorySingleton_ --> CTRL_: repositories
                deactivate RepositorySingleton_

                CTRL_ -> PLAT_ : getStoreCategoryRepository()
                activate PLAT_

                    PLAT_ -> CTRL_ : taskCategoryRepository
                deactivate PLAT_

                CTRL -> TaskCategoryRepository : getTaskCategoryByDescription(taskCategoryDescription)
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL : taskCategory
                deactivate TaskCategoryRepository
                    CTRL --> CTRL : taskCategory
            deactivate CTRL

            |||
            CTRL -> CTRL : getEmployeeFromSession()
            activate CTRL

                CTRL -> _APP: getInstance()
                activate _APP
                    _APP -> CTRL: appSession
                deactivate _APP


                CTRL -> APP: getCurrentSession()
                activate APP

                    APP --> CTRL: currentSession
                deactivate APP

                CTRL -> SESSAO: email = getUserEmail()
                activate SESSAO

                    SESSAO --> CTRL: email
                deactivate SESSAO


                CTRL -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> CTRL: organizationRepository
                deactivate PLAT


                CTRL -> OrganizationRepository: getOrganizationByEmployeeEmail(email)
                activate OrganizationRepository

                    loop [for each organization
                        OrganizationRepository -> ORG : anyEmployeeHasEmail(email)
                        activate ORG

                             ORG --> OrganizationRepository : true/false
                        deactivate ORG
                    end
                    OrganizationRepository --> CTRL : organization
                deactivate OrganizationRepository

                CTRL -> ORG: getEmployeeByEmail(email)
                activate ORG

                    ORG --> CTRL : employee
                deactivate ORG

                CTRL --> CTRL : employee
            deactivate CTRL

            |||
            CTRL -> ORG: createTask(employee, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, , taskCategory, employee)
            activate ORG

                ORG -> TAREFA**: create(employee, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, taskCategory, employee)
                ORG -> ORG: addTask (task)


                activate ORG
                    ORG -> ORG: validateTask(task)
                    activate ORG
                        ORG --> ORG
                    deactivate ORG

                    ORG --> ORG
                deactivate ORG

                ORG --> CTRL : task

            deactivate ORG

            CTRL --> UI: task
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml