@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

class Employee{
    name
    numberCitizen
    tin
    email
    phoneNumber
}

class Location{
    street
    zipCode
    stateUS
    city
    district
}

class StoreManager

class SystemAdministrator

class StoreNetworkManager

class Agent

Employee <|-- Agent
Employee <|-- StoreManager
Employee <|-- StoreNetworkManager
Employee <|-- SystemAdministrator
SystemAdministrator "1" -- "*" Employee: creates >
Employee "1" -- "1" Location: owns >


@enduml
